# Generated by Django 2.1.7 on 2019-03-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('address_line_1', models.CharField(max_length=1024)),
                ('address_line_2', models.CharField(max_length=1024)),
                ('company_zip_code', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_email', models.EmailField(blank=True, max_length=70)),
                ('parent_address_line_1', models.CharField(max_length=1024)),
                ('parent_address_line_2', models.CharField(max_length=1024)),
                ('parent_company_zip_code', models.CharField(max_length=1024)),
                ('parent_city', models.CharField(max_length=12)),
                ('parent_country', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_facility_name', models.CharField(max_length=1024)),
                ('practice_address_line_1', models.CharField(max_length=1024)),
                ('practice_address_line_2', models.CharField(max_length=1024)),
                ('practice_zip_code', models.CharField(max_length=1024)),
                ('practice_city', models.CharField(max_length=12)),
                ('practice_country', models.CharField(max_length=12)),
                ('practice_day', models.CharField(max_length=1024)),
                ('practice_time', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=1000)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='schedule.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=1024)),
                ('time', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_facility_name', models.CharField(max_length=1024)),
                ('tournament_address_line_1', models.CharField(max_length=1024)),
                ('tournament_address_line_2', models.CharField(max_length=1024)),
                ('tournament_zip_code', models.CharField(max_length=1024)),
                ('tournament_city', models.CharField(max_length=12)),
                ('tournament_country', models.CharField(max_length=12)),
                ('tournament_day', models.CharField(max_length=1024)),
                ('tournament_time', models.CharField(max_length=1024)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_schedules', to='schedule.Team')),
            ],
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_games', to='schedule.TournamentSchedule'),
        ),
        migrations.AddField(
            model_name='scheduledpractice',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_schedules', to='schedule.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='schedule.Team'),
        ),
        migrations.AddField(
            model_name='parentinformation',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_schedules', to='schedule.Player'),
        ),
        migrations.AddField(
            model_name='coach',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='schedule.Team'),
        ),
    ]
